DjangoAdminLTE/DjangoAdminLTE/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^dashboard/', include('dashboard.urls', namespace='dashboard'))
]

DjangoAdminLTE/dashboard/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name="index"),
    url(r'^login/$', views.LoginView.as_view(), name="login"),
    url(r'^blank/$', views.BlankView.as_view(), name="blank"),
    url(r'^buttons/$', views.ButtonsView.as_view(), name="buttons"),
    url(r'^flot/$', views.FlotView.as_view(), name="flot"),
    url(r'^forms/$', views.FormsView.as_view(), name="forms"),
    url(r'^grid/$', views.GridView.as_view(), name="grid"),
    url(r'^icons/$', views.IconsView.as_view(), name="icons"),
    url(r'^morris/$', views.MorrisView.as_view(), name="morris"),
    url(r'^notifications/$', views.NotificationsView.as_view(), name="notifications"),
    url(r'^panels/$', views.PanelsView.as_view(), name="panels"),
    url(r'^tables/$', views.TablesView.as_view(), name="tables"),
    url(r'^typography/$', views.TypographyView.as_view(), name="typography"),
]

DjangoAdminLTE/dashboard/models.py
from django.db import models

# Create your models here.

DjangoAdminLTE/dashboard/views.py
from django.views.generic import TemplateView
from django.shortcuts import render
from django.shortcuts import redirect
from django.http import HttpResponse
import json
from django.utils.translation import ugettext_lazy as _

from pprint import pprint
import traceback


class IndexView(TemplateView):
	template_name = "dashboard/index.html"

	def get_context_data(self, **kwargs):
		context = super(IndexView, self).get_context_data(**kwargs)
		context.update({'title': _("applications")})
		return context

class BlankView(TemplateView):
    template_name = "components/blank.html"

    def get_context_data(self, **kwargs):
        context = super(BlankView, self).get_context_data(**kwargs)
        context.update({'user':self.request.user})
        context.update({'title': "Blank Page"})
        return context


class ButtonsView(TemplateView):
    template_name = "components/buttons.html"

    def get_context_data(self, **kwargs):
        context = super(ButtonsView, self).get_context_data(**kwargs)
        context.update({'user':self.request.user})
        context.update({'title': "Buttons"})
        return context


class FlotView(TemplateView):
    template_name = "components/flot.html"

    def get_context_data(self, **kwargs):
        context = super(FlotView, self).get_context_data(**kwargs)
        context.update({'user':self.request.user})
        context.update({'title': "Flot Charts"})
        return context


class FormsView(TemplateView):
    template_name = "components/forms.html"

    def get_context_data(self, **kwargs):
        context = super(FormsView, self).get_context_data(**kwargs)
        context.update({'user':self.request.user})
        context.update({'title': "Forms"})
        return context


class GridView(TemplateView):
    template_name = "components/grid.html"

    def get_context_data(self, **kwargs):
        context = super(GridView, self).get_context_data(**kwargs)
        context.update({'user':self.request.user})
        context.update({'title': "Grid"})
        return context


class IconsView(TemplateView):
    template_name = "components/icons.html"

    def get_context_data(self, **kwargs):
        context = super(IconsView, self).get_context_data(**kwargs)
        context.update({'user':self.request.user})
        context.update({'title': "Icons"})
        return context


class LoginView(TemplateView):
    template_name = "components/login.html"

    def get_context_data(self, **kwargs):
        context = super(LoginView, self).get_context_data(**kwargs)
        context.update({'user':self.request.user})
        context.update({'title': "Log In"})
        return context


class MorrisView(TemplateView):
    template_name = "components/morris.html"

    def get_context_data(self, **kwargs):
        context = super(MorrisView, self).get_context_data(**kwargs)
        context.update({'user':self.request.user})
        context.update({'title': "Morris Charts"})
        return context


class NotificationsView(TemplateView):
    template_name = "components/notifications.html"

    def get_context_data(self, **kwargs):
        context = super(NotificationsView, self).get_context_data(**kwargs)
        context.update({'user':self.request.user})
        context.update({'title': "Notifications"})
        return context


class PanelsView(TemplateView):
    template_name = "components/panels-wells.html"

    def get_context_data(self, **kwargs):
        context = super(PanelsView, self).get_context_data(**kwargs)
        context.update({'user':self.request.user})
        context.update({'title': "Panels and Wells"})
        return context


class TablesView(TemplateView):
    template_name = "components/tables.html"

    def get_context_data(self, **kwargs):
        context = super(TablesView, self).get_context_data(**kwargs)
        context.update({'user':self.request.user})
        context.update({'title': "Tables"})
        return context

class TypographyView(TemplateView):
    template_name = "components/typography.html"

    def get_context_data(self, **kwargs):
        context = super(TypographyView, self).get_context_data(**kwargs)
        context.update({'user':self.request.user})
        context.update({'title': "Typography"})
        return context

DjangoAdminLTE/dashboard/templates/components/blank.html
{% extends "dashboard/base.html" %}


{% block content %}

<h1 class="page-header">Blank</h1>
    
{% endblock content %}

DjangoAdminLTE/dashboard/templates/components/buttons.html
{% extends "dashboard/base.html" %}
{% load staticfiles %}


{% block extrahead %}

<!-- Social Buttons CSS -->
<link href="{% static "bower_components/bootstrap-social/bootstrap-social.css" %}" rel="stylesheet">

{% endblock extrahead %}


{% block content %}
<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">Buttons</h1>
    </div>
    <!-- /.col-lg-12 -->
</div>
<!-- /.row -->
<div class="row">
    <div class="col-lg-6">
        <div class="panel panel-default">
            <div class="panel-heading">
                Default Buttons
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">
                <h4>Normal Buttons</h4>
                <p>
                    <button type="button" class="btn btn-default">Default</button>
                    <button type="button" class="btn btn-primary">Primary</button>
                    <button type="button" class="btn btn-success">Success</button>
                    <button type="button" class="btn btn-info">Info</button>
                    <button type="button" class="btn btn-warning">Warning</button>
                    <button type="button" class="btn btn-danger">Danger</button>
                    <button type="button" class="btn btn-link">Link</button>
                </p>
                <br>
                <h4>Disabled Buttons</h4>
                <p>
                    <button type="button" class="btn btn-default disabled">Default</button>
                    <button type="button" class="btn btn-primary disabled">Primary</button>
                    <button type="button" class="btn btn-success disabled">Success</button>
                    <button type="button" class="btn btn-info disabled">Info</button>
                    <button type="button" class="btn btn-warning disabled">Warning</button>
                    <button type="button" class="btn btn-danger disabled">Danger</button>
                    <button type="button" class="btn btn-link disabled">Link</button>
                </p>
                <br>
                <h4>Button Sizes</h4>
                <p>
                    <button type="button" class="btn btn-primary btn-lg">Large button</button>
                    <button type="button" class="btn btn-primary">Default button</button>
                    <button type="button" class="btn btn-primary btn-sm">Small button</button>
                    <button type="button" class="btn btn-primary btn-xs">Mini button</button>
                    <br>
                    <br>
                    <button type="button" class="btn btn-primary btn-lg btn-block">Block level button</button>
                </p>
            </div>
            <!-- /.panel-body -->
        </div>
        <!-- /.panel -->
        <div class="panel panel-default">
            <div class="panel-heading">
                Circle Icon Buttons with Font Awesome Icons
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">
                <h4>Normal Circle Buttons</h4>
                <button type="button" class="btn btn-default btn-circle"><i class="fa fa-check"></i>
                </button>
                <button type="button" class="btn btn-primary btn-circle"><i class="fa fa-list"></i>
                </button>
                <button type="button" class="btn btn-success btn-circle"><i class="fa fa-link"></i>
                </button>
                <button type="button" class="btn btn-info btn-circle"><i class="fa fa-check"></i>
                </button>
                <button type="button" class="btn btn-warning btn-circle"><i class="fa fa-times"></i>
                </button>
                <button type="button" class="btn btn-danger btn-circle"><i class="fa fa-heart"></i>
                </button>
                <br>
                <br>
                <h4>Large Circle Buttons</h4>
                <button type="button" class="btn btn-default btn-circle btn-lg"><i class="fa fa-check"></i>
                </button>
                <button type="button" class="btn btn-primary btn-circle btn-lg"><i class="fa fa-list"></i>
                </button>
                <button type="button" class="btn btn-success btn-circle btn-lg"><i class="fa fa-link"></i>
                </button>
                <button type="button" class="btn btn-info btn-circle btn-lg"><i class="fa fa-check"></i>
                </button>
                <button type="button" class="btn btn-warning btn-circle btn-lg"><i class="fa fa-times"></i>
                </button>
                <button type="button" class="btn btn-danger btn-circle btn-lg"><i class="fa fa-heart"></i>
                </button>
                <br>
                <br>
                <h4>Extra Large Circle Buttons</h4>
                <button type="button" class="btn btn-default btn-circle btn-xl"><i class="fa fa-check"></i>
                </button>
                <button type="button" class="btn btn-primary btn-circle btn-xl"><i class="fa fa-list"></i>
                </button>
                <button type="button" class="btn btn-success btn-circle btn-xl"><i class="fa fa-link"></i>
                </button>
                <button type="button" class="btn btn-info btn-circle btn-xl"><i class="fa fa-check"></i>
                </button>
                <button type="button" class="btn btn-warning btn-circle btn-xl"><i class="fa fa-times"></i>
                </button>
                <button type="button" class="btn btn-danger btn-circle btn-xl"><i class="fa fa-heart"></i>
                </button>
            </div>
            <!-- /.panel-body -->
        </div>
        <!-- /.panel -->
    </div>
    <!-- /.col-lg-6 -->
    <div class="col-lg-6">
        <div class="panel panel-default">
            <div class="panel-heading">
                Outline Buttons with Smooth Transition
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">
                <h4>Outline Buttons</h4>
                <p>
                    <button type="button" class="btn btn-outline btn-default">Default</button>
                    <button type="button" class="btn btn-outline btn-primary">Primary</button>
                    <button type="button" class="btn btn-outline btn-success">Success</button>
                    <button type="button" class="btn btn-outline btn-info">Info</button>
                    <button type="button" class="btn btn-outline btn-warning">Warning</button>
                    <button type="button" class="btn btn-outline btn-danger">Danger</button>
                    <button type="button" class="btn btn-outline btn-link">Link</button>
                </p>
                <br>
                <h4>Outline Button Sizes</h4>
                <p>
                    <button type="button" class="btn btn-outline btn-primary btn-lg">Large button</button>
                    <button type="button" class="btn btn-outline btn-primary">Default button</button>
                    <button type="button" class="btn btn-outline btn-primary btn-sm">Small button</button>
                    <button type="button" class="btn btn-outline btn-primary btn-xs">Mini button</button>
                    <br>
                    <br>
                    <button type="button" class="btn btn-outline btn-primary btn-lg btn-block">Block level button</button>
                </p>
            </div>
            <!-- /.panel-body -->
        </div>
        <!-- /.panel -->
        <div class="panel panel-default">
            <div class="panel-heading">
                Social Buttons with Font Awesome Icons
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">
                <h4>Social Buttons</h4>
                <a class="btn btn-block btn-social btn-bitbucket">
                    <i class="fa fa-bitbucket"></i> Sign in with Bitbucket
                </a>
                <a class="btn btn-block btn-social btn-dropbox">
                    <i class="fa fa-dropbox"></i> Sign in with Dropbox
                </a>
                <a class="btn btn-block btn-social btn-facebook">
                    <i class="fa fa-facebook"></i> Sign in with Facebook
                </a>
                <a class="btn btn-block btn-social btn-flickr">
                    <i class="fa fa-flickr"></i> Sign in with Flickr
                </a>
                <a class="btn btn-block btn-social btn-github">
                    <i class="fa fa-github"></i> Sign in with GitHub
                </a>
                <a class="btn btn-block btn-social btn-google-plus">
                    <i class="fa fa-google-plus"></i> Sign in with Google
                </a>
                <a class="btn btn-block btn-social btn-instagram">
                    <i class="fa fa-instagram"></i> Sign in with Instagram
                </a>
                <a class="btn btn-block btn-social btn-linkedin">
                    <i class="fa fa-linkedin"></i> Sign in with LinkedIn
                </a>
                <a class="btn btn-block btn-social btn-pinterest">
                    <i class="fa fa-pinterest"></i> Sign in with Pinterest
                </a>
                <a class="btn btn-block btn-social btn-tumblr">
                    <i class="fa fa-tumblr"></i> Sign in with Tumblr
                </a>
                <a class="btn btn-block btn-social btn-twitter">
                    <i class="fa fa-twitter"></i> Sign in with Twitter
                </a>
                <a class="btn btn-block btn-social btn-vk">
                    <i class="fa fa-vk"></i> Sign in with VK
                </a>

                <hr>

                <div class="text-center">
                    <a class="btn btn-social-icon btn-bitbucket"><i class="fa fa-bitbucket"></i></a>
                    <a class="btn btn-social-icon btn-dropbox"><i class="fa fa-dropbox"></i></a>
                    <a class="btn btn-social-icon btn-facebook"><i class="fa fa-facebook"></i></a>
                    <a class="btn btn-social-icon btn-flickr"><i class="fa fa-flickr"></i></a>
                    <a class="btn btn-social-icon btn-github"><i class="fa fa-github"></i></a>
                    <a class="btn btn-social-icon btn-google-plus"><i class="fa fa-google-plus"></i></a>
                    <a class="btn btn-social-icon btn-instagram"><i class="fa fa-instagram"></i></a>
                    <a class="btn btn-social-icon btn-linkedin"><i class="fa fa-linkedin"></i></a>
                    <a class="btn btn-social-icon btn-pinterest"><i class="fa fa-pinterest"></i></a>
                    <a class="btn btn-social-icon btn-tumblr"><i class="fa fa-tumblr"></i></a>
                    <a class="btn btn-social-icon btn-twitter"><i class="fa fa-twitter"></i></a>
                    <a class="btn btn-social-icon btn-vk"><i class="fa fa-vk"></i></a>
                </div>
            </div>
            <!-- /.panel-body -->
        </div>
        <!-- /.panel -->
    </div>
    <!-- /.col-lg-6 -->
</div>
<!-- /.row -->
    
{% endblock content %}

DjangoAdminLTE/dashboard/templates/components/flot.html
{% extends "dashboard/base.html" %}
{% load staticfiles %}

{% block extrahead %}

<!-- Timeline CSS -->
<link href="{% static "css/timeline.css" %}" rel="stylesheet">

<!-- Morris Charts CSS -->
<link href="{% static "bower_components/morrisjs/morris.css" %}" rel="stylesheet">    

{% endblock extrahead %}


{% block content %}

<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">Flot</h1>
    </div>
    <!-- /.col-lg-12 -->
</div>
<!-- /.row -->
<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                Line Chart Example
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">
                <div class="flot-chart">
                    <div class="flot-chart-content" id="flot-line-chart"></div>
                </div>
            </div>
            <!-- /.panel-body -->
        </div>
        <!-- /.panel -->
    </div>
    <!-- /.col-lg-12 -->
    <div class="col-lg-6">
        <div class="panel panel-default">
            <div class="panel-heading">
                Pie Chart Example
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">
                <div class="flot-chart">
                    <div class="flot-chart-content" id="flot-pie-chart"></div>
                </div>
            </div>
            <!-- /.panel-body -->
        </div>
        <!-- /.panel -->
    </div>
    <!-- /.col-lg-6 -->
    <div class="col-lg-6">
        <div class="panel panel-default">
            <div class="panel-heading">
                Multiple Axes Line Chart Example
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">
                <div class="flot-chart">
                    <div class="flot-chart-content" id="flot-line-chart-multi"></div>
                </div>
            </div>
            <!-- /.panel-body -->
        </div>
        <!-- /.panel -->
    </div>
    <!-- /.col-lg-6 -->
    <div class="col-lg-6">
        <div class="panel panel-default">
            <div class="panel-heading">
                Moving Line Chart Example
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">
                <div class="flot-chart">
                    <div class="flot-chart-content" id="flot-line-chart-moving"></div>
                </div>
            </div>
            <!-- /.panel-body -->
        </div>
        <!-- /.panel -->
    </div>
    <!-- /.col-lg-6 -->
    <div class="col-lg-6">
        <div class="panel panel-default">
            <div class="panel-heading">
                Bar Chart Example
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">
                <div class="flot-chart">
                    <div class="flot-chart-content" id="flot-bar-chart"></div>
                </div>
            </div>
            <!-- /.panel-body -->
        </div>
        <!-- /.panel -->
    </div>
    <!-- /.col-lg-6 -->
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                Flot Charts Usage
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">
                <p>Flot is a pure JavaScript plotting library for jQuery, with a focus on simple usage, attractive looks, and interactive features. In SB Admin, we are using the most recent version of Flot along with a few plugins to enhance the user experience. The Flot plugins being used are the tooltip plugin for hoverable tooltips, and the resize plugin for fully responsive charts. The documentation for Flot Charts is available on their website, <a target="_blank" href="http://www.flotcharts.org/">http://www.flotcharts.org/</a>.</p>
                <a target="_blank" class="btn btn-default btn-lg btn-block" href="http://www.flotcharts.org/">View Flot Charts Documentation</a>
            </div>
            <!-- /.panel-body -->
        </div>
        <!-- /.panel -->
    </div>
    <!-- /.col-lg-6 -->
</div>
<!-- /.row -->
    
{% endblock content %}


{% block extrajs %}

<!-- Flot Charts JavaScript -->
<script src="{% static "bower_components/flot/excanvas.min.js" %}"></script>
<script src="{% static "bower_components/flot/jquery.flot.js" %}"></script>
<script src="{% static "bower_components/flot/jquery.flot.pie.js" %}"></script>
<script src="{% static "bower_components/flot/jquery.flot.resize.js" %}"></script>
<script src="{% static "bower_components/flot/jquery.flot.time.js" %}"></script>
<script src="{% static "bower_components/flot.tooltip/js/jquery.flot.tooltip.min.js" %}"></script>
<script src="{% static "js/flot-data.js" %}"></script>    

{% endblock extrajs %}

DjangoAdminLTE/dashboard/templates/components/login.html
{% extends "layout/base.html" %}


{% block basecontent %}

<div class="container">
    <div class="row">
        <div class="col-md-4 col-md-offset-4">
            <div class="login-panel panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">Please Sign In</h3>
                </div>
                <div class="panel-body">
                    <form role="form">
                        <fieldset>
                            <div class="form-group">
                                <input class="form-control" placeholder="E-mail" name="email" type="email" autofocus>
                            </div>
                            <div class="form-group">
                                <input class="form-control" placeholder="Password" name="password" type="password" value="">
                            </div>
                            <div class="checkbox">
                                <label>
                                    <input name="remember" type="checkbox" value="Remember Me">Remember Me
                                </label>
                            </div>
                            <!-- Change this to a button or input when using this as a form -->
                            <a href="{% url 'dashboard:index' %}" class="btn btn-lg btn-success btn-block">Login</a>
                        </fieldset>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
    
{% endblock basecontent %}

DjangoAdminLTE/dashboard/templates/components/morris.html
{% extends "dashboard/base.html" %}
{% load staticfiles %}

{% block extrahead %}
    
<!-- Morris Charts CSS -->
<link href="{% static "bower_components/morrisjs/morris.css" %}" rel="stylesheet">

{% endblock extrahead %}


{% block content %}
    
<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">Morris.js Charts</h1>
    </div>
    <!-- /.col-lg-12 -->
</div>
<!-- /.row -->
<div class="row">
    <div class="col-lg-6">
        <div class="panel panel-default">
            <div class="panel-heading">
                Area Chart Example
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">
                <div id="morris-area-chart"></div>
            </div>
            <!-- /.panel-body -->
        </div>
        <!-- /.panel -->
    </div>
    <!-- /.col-lg-6 -->
    <div class="col-lg-6">
        <div class="panel panel-default">
            <div class="panel-heading">
                Bar Chart Example
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">
                <div id="morris-bar-chart"></div>
            </div>
            <!-- /.panel-body -->
        </div>
        <!-- /.panel -->
    </div>
    <!-- /.col-lg-6 -->
    <div class="col-lg-6">
        <div class="panel panel-default">
            <div class="panel-heading">
                Line Chart Example
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">
                <div id="morris-line-chart"></div>
            </div>
            <!-- /.panel-body -->
        </div>
        <!-- /.panel -->
    </div>
    <!-- /.col-lg-6 -->
    <div class="col-lg-6">
        <div class="panel panel-default">
            <div class="panel-heading">
                Donut Chart Example
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">
                <div id="morris-donut-chart"></div>
            </div>
            <!-- /.panel-body -->
        </div>
        <!-- /.panel -->
    </div>
    <!-- /.col-lg-6 -->
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                Morris.js Usage
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">
                <p>Morris.js is a jQuery based charting plugin created by Olly Smith. In SB Admin, we are using the most recent version of Morris.js which includes the resize function, which makes the charts fully responsive. The documentation for Morris.js is available on their website, <a target="_blank" href="http://morrisjs.github.io/morris.js/">http://morrisjs.github.io/morris.js/</a>.</p>
                <a target="_blank" class="btn btn-default btn-lg btn-block" href="http://morrisjs.github.io/morris.js/">View Morris.js Documentation</a>
            </div>
            <!-- /.panel-body -->
        </div>
        <!-- /.panel -->
    </div>
    <!-- /.col-lg-6 -->
</div>
<!-- /.row -->

{% endblock content %}


{% block extrajs %}

<!-- Morris Charts JavaScript -->
<script src="{% static "bower_components/raphael/raphael-min.js" %}"></script>
<script src="{% static "bower_components/morrisjs/morris.min.js" %}"></script>
<script src="{% static "js/morris-data.js" %}"></script>

{% endblock extrajs %}

DjangoAdminLTE/dashboard/templates/components/setting.html
{% extends "dashboard/base.html" %}

{%block content %}

<div id = "alert_placeholder">

</div>

{% if MaxRetryError %}
<div class="alert alert-warning">
    <strong>HttpError:</strong>
        <li>{{error_message}}</li>
</div>
{% endif %}

{% if ApiException %}
	<div class="alert alert-error">
    <strong>ApiExceptionError:</strong>
        <li>{{api_exception_message}}</li>
</div>
{% endif %}

{% if error_type %}
<div class="alert alert-warning">
    <a href="#" class="close" data-dismiss="alert">
        &times;
    </a>
    <strong>{{error_type}}</strong>
      <li>{{ error_message }}</li>
</div>
{% endif %}

<div class="col-lg-8">
	<div class="panel panel-primary">
		<div class="panel-heading" align="center">
			<h3>{{ form.title.value }}</h3>
		</div>
		<div class="panel-body" align="center">
		<div class="form-group" align="left">
			<form action="" class="form-horizontal" method="post" accept-charset="utf-8">
			{% csrf_token %}
	        <div class="box box-primary">
	            <div class="box-body">
	            	{% for field in form %}
	            	{% ifnotequal field.label 'title' %}
	            		{{field.label_tag}}
	            		{{field}}
                	{% endifnotequal %}
	            	{% endfor %}
	            </div>
				<button type="submit" name="submit" class="btn btn-info pull-right">Save</button>
				<a href="{{cancel_url}}" class="btn btn-default pull-right">Cancel</a>
			</div>
	     	</form>
		</div>
		</div>
	</div>
</div>

{% endblock content %}

DjangoAdminLTE/dashboard/templates/dashboard/index.html
{% extends "dashboard/base.html" %}
{% load i18n %}
{% load staticfiles %}
{% block extrahead %}

{% endblock extrahead %}

{% block content %}


<div class="row">

</div>
<!-- /.row -->
<div class="row">
</div>


{% endblock content %}

{% block extrajs %}

{% endblock extrajs %}